const en = [
  {
    code: 'Backquote',
    class: 'key no-letter',
    upperCapsValue: '`',
    lowerValue: '`',
    upperValue: '~',
  },
  {
    code: 'Digit1',
    class: 'key no-letter',
    upperCapsValue: '1',
    lowerValue: '1',
    upperValue: '!',
  },
  {
    code: 'Digit2',
    class: 'key no-letter',
    upperCapsValue: '2',
    lowerValue: '2',
    upperValue: '@',
  },
  {
    code: 'Digit3',
    class: 'key no-letter',
    upperCapsValue: '3',
    lowerValue: '3',
    upperValue: '#',
  },
  {
    code: 'Digit4',
    class: 'key no-letter',
    upperCapsValue: '4',
    lowerValue: '4',
    upperValue: '$',
  },
  {
    code: 'Digit5',
    class: 'key no-letter',
    upperCapsValue: '5',
    lowerValue: '5',
    upperValue: '%',
  },
  {
    code: 'Digit6',
    class: 'key no-letter',
    upperCapsValue: '6',
    lowerValue: '6',
    upperValue: '^',
  },
  {
    code: 'Digit7',
    class: 'key no-letter',
    upperCapsValue: '7',
    lowerValue: '7',
    upperValue: '&',
  },
  {
    code: 'Digit8',
    class: 'key no-letter',
    upperCapsValue: '8',
    lowerValue: '8',
    upperValue: '*',
  },
  {
    code: 'Digit9',
    class: 'key no-letter',
    upperCapsValue: '9',
    lowerValue: '9',
    upperValue: '(',
  },
  {
    code: 'Digit0',
    class: 'key no-letter',
    upperCapsValue: '0',
    lowerValue: '0',
    upperValue: ')',
  },
  {
    code: 'Minus',
    class: 'key no-letter',
    upperCapsValue: '-',
    lowerValue: '-',
    upperValue: '_',
  },
  {
    code: 'Equal',
    class: 'key no-letter',
    upperCapsValue: '=',
    lowerValue: '=',
    upperValue: '+',
  },
  {
    code: 'Backspace',
    class: 'func backspace',
    upperCapsValue: 'backspace',
    lowerValue: 'backspace',
    upperValue: 'backspace',
  },
  {
    code: 'Tab',
    class: 'func tab',
    upperCapsValue: 'tab',
    lowerValue: 'tab',
    upperValue: 'tab',
  },
  {
    code: 'KeyQ',
    class: 'key letter',
    upperCapsValue: 'Q',
    lowerValue: 'q',
    upperValue: 'Q',
  },
  {
    code: 'KeyW',
    class: 'key letter',
    upperCapsValue: 'W',
    lowerValue: 'w',
    upperValue: 'W',
  },
  {
    code: 'KeyE',
    class: 'key letter',
    upperCapsValue: 'E',
    lowerValue: 'e',
    upperValue: 'E',
  },
  {
    code: 'KeyR',
    class: 'key letter',
    upperCapsValue: 'R',
    lowerValue: 'r',
    upperValue: 'R',
  },
  {
    code: 'KeyT',
    class: 'key letter',
    upperCapsValue: 'T',
    lowerValue: 't',
    upperValue: 'T',
  },
  {
    code: 'KeyY',
    class: 'key letter',
    upperCapsValue: 'Y',
    lowerValue: 'y',
    upperValue: 'Y',
  },
  {
    code: 'KeyU',
    class: 'key letter',
    upperCapsValue: 'U',
    lowerValue: 'u',
    upperValue: 'U',
  },
  {
    code: 'KeyI',
    class: 'key letter',
    upperCapsValue: 'I',
    lowerValue: 'i',
    upperValue: 'I',
  },
  {
    code: 'KeyO',
    class: 'key letter',
    upperCapsValue: 'O',
    lowerValue: 'o',
    upperValue: 'O',
  },
  {
    code: 'KeyP',
    class: 'key letter',
    upperCapsValue: 'P',
    lowerValue: 'p',
    upperValue: 'P',
  },
  {
    code: 'BracketLeft',
    class: 'key no-letter',
    upperCapsValue: '[',
    lowerValue: '[',
    upperValue: '{',
  },
  {
    code: 'BracketRight',
    class: 'key no-letter',
    upperCapsValue: ']',
    lowerValue: ']',
    upperValue: '}',
  },
  {
    code: 'Delete',
    class: 'func delete',
    upperCapsValue: 'delete',
    lowerValue: 'delete',
    upperValue: 'delete',
  },
  {
    code: 'CapsLock',
    class: 'func capslock',
    upperCapsValue: 'capslock',
    lowerValue: 'capslock',
    upperValue: 'capslock',
  },
  {
    code: 'KeyA',
    class: 'key letter',
    upperCapsValue: 'A',
    lowerValue: 'a',
    upperValue: 'A',
  },
  {
    code: 'KeyS',
    class: 'key letter',
    upperCapsValue: 'S',
    lowerValue: 's',
    upperValue: 'S',
  },
  {
    code: 'KeyD',
    class: 'key letter',
    upperCapsValue: 'D',
    lowerValue: 'd',
    upperValue: 'D',
  },
  {
    code: 'KeyF',
    class: 'key letter',
    upperCapsValue: 'F',
    lowerValue: 'f',
    upperValue: 'F',
  },
  {
    code: 'KeyG',
    class: 'key letter',
    upperCapsValue: 'G',
    lowerValue: 'g',
    upperValue: 'G',
  },
  {
    code: 'KeyH',
    class: 'key letter',
    upperCapsValue: 'H',
    lowerValue: 'h',
    upperValue: 'H',
  },
  {
    code: 'KeyJ',
    class: 'key letter',
    upperCapsValue: 'J',
    lowerValue: 'j',
    upperValue: 'J',
  },
  {
    code: 'KeyK',
    class: 'key letter',
    upperCapsValue: 'K',
    lowerValue: 'k',
    upperValue: 'K',
  },
  {
    code: 'KeyL',
    class: 'key letter',
    upperCapsValue: 'L',
    lowerValue: 'l',
    upperValue: 'L',
  },
  {
    code: 'Semicolon',
    class: 'key no-letter',
    upperCapsValue: ';',
    lowerValue: ';',
    upperValue: ':',
  },
  {
    code: 'Quote',
    class: 'key no-letter',
    upperCapsValue: '\'',
    lowerValue: '\'',
    upperValue: '"',
  },
  {
    code: 'Enter',
    class: 'func enter',
    upperCapsValue: 'enter',
    lowerValue: 'enter',
    upperValue: 'enter',
  },
  {
    code: 'ShiftLeft',
    class: 'func shiftleft',
    upperCapsValue: 'shift',
    lowerValue: 'shift',
    upperValue: 'shift',
  },
  {
    code: 'KeyZ',
    class: 'key letter',
    upperCapsValue: 'Z',
    lowerValue: 'z',
    upperValue: 'Z',
  },
  {
    code: 'KeyX',
    class: 'key letter',
    upperCapsValue: 'X',
    lowerValue: 'x',
    upperValue: 'X',
  },
  {
    code: 'KeyC',
    class: 'key letter',
    upperCapsValue: 'C',
    lowerValue: 'c',
    upperValue: 'C',
  },
  {
    code: 'KeyV',
    class: 'key letter',
    upperCapsValue: 'V',
    lowerValue: 'v',
    upperValue: 'V',
  },
  {
    code: 'KeyB',
    class: 'key letter',
    upperCapsValue: 'B',
    lowerValue: 'b',
    upperValue: 'B',
  },
  {
    code: 'KeyN',
    class: 'key letter',
    upperCapsValue: 'N',
    lowerValue: 'n',
    upperValue: 'N',
  },
  {
    code: 'KeyM',
    class: 'key letter',
    upperCapsValue: 'M',
    lowerValue: 'm',
    upperValue: 'M',
  },
  {
    code: 'Comma',
    class: 'key no-letter',
    upperCapsValue: ',',
    lowerValue: ',',
    upperValue: '<',
  },
  {
    code: 'Period',
    class: 'key no-letter',
    upperCapsValue: '.',
    lowerValue: '.',
    upperValue: '>',
  },
  {
    code: 'Slash',
    class: 'key no-letter',
    upperCapsValue: '/',
    lowerValue: '/',
    upperValue: '?',
  },
  {
    code: 'Backslash',
    class: 'key no-letter',
    upperCapsValue: '\\',
    lowerValue: '\\',
    upperValue: '|',
  },
  {
    code: 'ArrowUp',
    class: 'func arrowup',
    upperCapsValue: '&#9650',
    lowerValue: '&#9650',
    upperValue: '&#9650',
  },
  {
    code: 'ShiftRight',
    class: 'func shiftright',
    upperCapsValue: 'shift',
    lowerValue: 'shift',
    upperValue: 'shift',
  },
  {
    code: 'ControlLeft',
    class: 'func controlleft',
    upperCapsValue: 'ctrl',
    lowerValue: 'ctrl',
    upperValue: 'ctrl',
  },
  {
    code: 'MetaLeft',
    class: 'func metaleft',
    upperCapsValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
    lowerValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
    upperValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
  },
  {
    code: 'AltLeft',
    class: 'func altleft',
    upperCapsValue: 'alt',
    lowerValue: 'alt',
    upperValue: 'alt',
  },
  {
    code: 'Space',
    class: 'func space',
    upperCapsValue: '',
    lowerValue: '',
    upperValue: '',
  },
  {
    code: 'AltRight',
    class: 'func altright',
    upperCapsValue: 'alt',
    lowerValue: 'alt',
    upperValue: 'alt',
  },
  {
    code: 'ControlRight',
    class: 'func controlright',
    upperCapsValue: 'ctrl',
    lowerValue: 'ctrl',
    upperValue: 'ctrl',
  },
  {
    code: 'ArrowLeft',
    class: 'func arrowleft',
    upperCapsValue: '&#9668',
    lowerValue: '&#9668',
    upperValue: '&#9668',
  },
  {
    code: 'ArrowDown',
    class: 'func arrowdown',
    upperCapsValue: '&#9660',
    lowerValue: '&#9660',
    upperValue: '&#9660',
  },
  {
    code: 'ArrowRight',
    class: 'func arrowright',
    upperCapsValue: '&#9658',
    lowerValue: '&#9658',
    upperValue: '&#9658',
  },
];

export default en;
