const ru = [
  {
    code: 'Backquote',
    class: 'key letter',
    upperCapsValue: 'Ё',
    lowerValue: 'ё',
    upperValue: 'Ё',
  },
  {
    code: 'Digit1',
    class: 'key no-letter',
    upperCapsValue: '1',
    lowerValue: '1',
    upperValue: '!',
  },
  {
    code: 'Digit2',
    class: 'key no-letter',
    upperCapsValue: '2',
    lowerValue: '2',
    upperValue: '"',
  },
  {
    code: 'Digit3',
    class: 'key no-letter',
    upperCapsValue: '3',
    lowerValue: '3',
    upperValue: '№',
  },
  {
    code: 'Digit4',
    class: 'key no-letter',
    upperCapsValue: '4',
    lowerValue: '4',
    upperValue: ';',
  },
  {
    code: 'Digit5',
    class: 'key no-letter',
    upperCapsValue: '5',
    lowerValue: '5',
    upperValue: '%',
  },
  {
    code: 'Digit6',
    class: 'key no-letter',
    upperCapsValue: '6',
    lowerValue: '6',
    upperValue: ':',
  },
  {
    code: 'Digit7',
    class: 'key no-letter',
    upperCapsValue: '7',
    lowerValue: '7',
    upperValue: '?',
  },
  {
    code: 'Digit8',
    class: 'key no-letter',
    upperCapsValue: '8',
    lowerValue: '8',
    upperValue: '*',
  },
  {
    code: 'Digit9',
    class: 'key no-letter',
    upperCapsValue: '9',
    lowerValue: '9',
    upperValue: '(',
  },
  {
    code: 'Digit0',
    class: 'key no-letter',
    upperCapsValue: '0',
    lowerValue: '0',
    upperValue: ')',
  },
  {
    code: 'Minus',
    class: 'key no-letter',
    upperCapsValue: '-',
    lowerValue: '-',
    upperValue: '_',
  },
  {
    code: 'Equal',
    class: 'key no-letter',
    upperCapsValue: '=',
    lowerValue: '=',
    upperValue: '+',
  },
  {
    code: 'Backspace',
    class: 'func backspace',
    upperCapsValue: 'backspace',
    lowerValue: 'backspace',
    upperValue: 'backspace',
  },
  {
    code: 'Tab',
    class: 'func tab',
    upperCapsValue: 'tab',
    lowerValue: 'tab',
    upperValue: 'tab',
  },
  {
    code: 'KeyQ',
    class: 'key letter',
    upperCapsValue: 'Й',
    lowerValue: 'й',
    upperValue: 'Й',
  },
  {
    code: 'KeyW',
    class: 'key letter',
    upperCapsValue: 'Ц',
    lowerValue: 'ц',
    upperValue: 'Ц',
  },
  {
    code: 'KeyE',
    class: 'key letter',
    upperCapsValue: 'У',
    lowerValue: 'у',
    upperValue: 'У',
  },
  {
    code: 'KeyR',
    class: 'key letter',
    upperCapsValue: 'К',
    lowerValue: 'к',
    upperValue: 'К',
  },
  {
    code: 'KeyT',
    class: 'key letter',
    upperCapsValue: 'Е',
    lowerValue: 'е',
    upperValue: 'Е',
  },
  {
    code: 'KeyY',
    class: 'key letter',
    upperCapsValue: 'Н',
    lowerValue: 'н',
    upperValue: 'Н',
  },
  {
    code: 'KeyU',
    class: 'key letter',
    upperCapsValue: 'Г',
    lowerValue: 'г',
    upperValue: 'Г',
  },
  {
    code: 'KeyI',
    class: 'key letter',
    upperCapsValue: 'Ш',
    lowerValue: 'ш',
    upperValue: 'Ш',
  },
  {
    code: 'KeyO',
    class: 'key letter',
    upperCapsValue: 'Щ',
    lowerValue: 'щ',
    upperValue: 'Щ',
  },
  {
    code: 'KeyP',
    class: 'key letter',
    upperCapsValue: 'З',
    lowerValue: 'з',
    upperValue: 'З',
  },
  {
    code: 'BracketLeft',
    class: 'key letter',
    upperCapsValue: 'Х',
    lowerValue: 'х',
    upperValue: 'Х',
  },
  {
    code: 'BracketRight',
    class: 'key letter',
    upperCapsValue: 'Ъ',
    lowerValue: 'ъ',
    upperValue: 'Ъ',
  },
  {
    code: 'Delete',
    class: 'func delete',
    upperCapsValue: 'delete',
    lowerValue: 'delete',
    upperValue: 'delete',
  },
  {
    code: 'CapsLock',
    class: 'func capslock',
    upperCapsValue: 'capslock',
    lowerValue: 'capslock',
    upperValue: 'capslock',
  },
  {
    code: 'KeyA',
    class: 'key letter',
    upperCapsValue: 'Ф',
    lowerValue: 'ф',
    upperValue: 'Ф',
  },
  {
    code: 'KeyS',
    class: 'key letter',
    upperCapsValue: 'Ы',
    lowerValue: 'ы',
    upperValue: 'Ы',
  },
  {
    code: 'KeyD',
    class: 'key letter',
    upperCapsValue: 'В',
    lowerValue: 'в',
    upperValue: 'В',
  },
  {
    code: 'KeyF',
    class: 'key letter',
    upperCapsValue: 'А',
    lowerValue: 'а',
    upperValue: 'А',
  },
  {
    code: 'KeyG',
    class: 'key letter',
    upperCapsValue: 'П',
    lowerValue: 'п',
    upperValue: 'П',
  },
  {
    code: 'KeyH',
    class: 'key letter',
    upperCapsValue: 'Р',
    lowerValue: 'р',
    upperValue: 'Р',
  },
  {
    code: 'KeyJ',
    class: 'key letter',
    upperCapsValue: 'О',
    lowerValue: 'о',
    upperValue: 'О',
  },
  {
    code: 'KeyK',
    class: 'key letter',
    upperCapsValue: 'Л',
    lowerValue: 'л',
    upperValue: 'Л',
  },
  {
    code: 'KeyL',
    class: 'key letter',
    upperCapsValue: 'Д',
    lowerValue: 'д',
    upperValue: 'Д',
  },
  {
    code: 'Semicolon',
    class: 'key letter',
    upperCapsValue: 'Ж',
    lowerValue: 'ж',
    upperValue: 'Ж',
  },
  {
    code: 'Quote',
    class: 'key letter',
    upperCapsValue: 'Э',
    lowerValue: 'э',
    upperValue: 'Э',
  },
  {
    code: 'Enter',
    class: 'func enter',
    upperCapsValue: 'enter',
    lowerValue: 'enter',
    upperValue: 'enter',
  },
  {
    code: 'ShiftLeft',
    class: 'func shiftleft',
    upperCapsValue: 'shift',
    lowerValue: 'shift',
    upperValue: 'shift',
  },
  {
    code: 'KeyZ',
    class: 'key letter',
    upperCapsValue: 'Я',
    lowerValue: 'я',
    upperValue: 'Я',
  },
  {
    code: 'KeyX',
    class: 'key letter',
    upperCapsValue: 'Ч',
    lowerValue: 'ч',
    upperValue: 'Ч',
  },
  {
    code: 'KeyC',
    class: 'key letter',
    upperCapsValue: 'С',
    lowerValue: 'с',
    upperValue: 'С',
  },
  {
    code: 'KeyV',
    class: 'key letter',
    upperCapsValue: 'М',
    lowerValue: 'м',
    upperValue: 'М',
  },
  {
    code: 'KeyB',
    class: 'key letter',
    upperCapsValue: 'И',
    lowerValue: 'и',
    upperValue: 'И',
  },
  {
    code: 'KeyN',
    class: 'key letter',
    upperCapsValue: 'Т',
    lowerValue: 'т',
    upperValue: 'Т',
  },
  {
    code: 'KeyM',
    class: 'key letter',
    upperCapsValue: 'Ь',
    lowerValue: 'ь',
    upperValue: 'Ь',
  },
  {
    code: 'Comma',
    class: 'key letter',
    upperCapsValue: 'Б',
    lowerValue: 'б',
    upperValue: 'Б',
  },
  {
    code: 'Period',
    class: 'key letter',
    upperCapsValue: 'Ю',
    lowerValue: 'ю',
    upperValue: 'Ю',
  },
  {
    code: 'Slash',
    class: 'key no-letter',
    upperCapsValue: '.',
    lowerValue: '.',
    upperValue: ',',
  },
  {
    code: 'Backslash',
    class: 'key no-letter',
    upperCapsValue: '\\',
    lowerValue: '\\',
    upperValue: '/',
  },
  {
    code: 'ArrowUp',
    class: 'func arrowup',
    upperCapsValue: '&#9650',
    lowerValue: '&#9650',
    upperValue: '&#9650',
  },
  {
    code: 'ShiftRight',
    class: 'func shiftright',
    upperCapsValue: 'shift',
    lowerValue: 'shift',
    upperValue: 'shift',
  },
  {
    code: 'ControlLeft',
    class: 'func controlleft',
    upperCapsValue: 'ctrl',
    lowerValue: 'ctrl',
    upperValue: 'ctrl',
  },
  {
    code: 'MetaLeft',
    class: 'func metaleft',
    upperCapsValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
    lowerValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
    upperValue: '<svg class="win"><use xlink:href="./assets/sprite.svg#win"></use></svg>',
  },
  {
    code: 'AltLeft',
    class: 'func altleft',
    upperCapsValue: 'alt',
    lowerValue: 'alt',
    upperValue: 'alt',
  },
  {
    code: 'Space',
    class: 'func space',
    upperCapsValue: '',
    lowerValue: '',
    upperValue: '',
  },
  {
    code: 'AltRight',
    class: 'func altright',
    upperCapsValue: 'alt',
    lowerValue: 'alt',
    upperValue: 'alt',
  },
  {
    code: 'ControlRight',
    class: 'func controlright',
    upperCapsValue: 'ctrl',
    lowerValue: 'ctrl',
    upperValue: 'ctrl',
  },
  {
    code: 'ArrowLeft',
    class: 'func arrowleft',
    upperCapsValue: '&#9668',
    lowerValue: '&#9668',
    upperValue: '&#9668',
  },
  {
    code: 'ArrowDown',
    class: 'func arrowdown',
    upperCapsValue: '&#9660',
    lowerValue: '&#9660',
    upperValue: '&#9660',
  },
  {
    code: 'ArrowRight',
    class: 'func arrowright',
    upperCapsValue: '&#9658',
    lowerValue: '&#9658',
    upperValue: '&#9658',
  },
];

export default ru;
